# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/d1/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),d1)

$(call add-radio-file-sha1-checked,radio/cm.bin_SM-N970F,40ebf495dc7d6ddf4292c6862cd203c617bf5a97)
$(call add-radio-file-sha1-checked,radio/dqmdbg.img_SM-N970F,487728143785bbda7e94891c510861036c5a317e)
$(call add-radio-file-sha1-checked,radio/keystorage.bin_SM-N970F,36d364a7880f6520c9ec2ae8f49e89f4072ce8bc)
$(call add-radio-file-sha1-checked,radio/models,c55950824b82b88c5f0fcade4700eec3f44c9cb8)
$(call add-radio-file-sha1-checked,radio/modem.bin_SM-N970F,e71c5c7a8e5de3fc97d0b577c6eb2f6cc228977a)
$(call add-radio-file-sha1-checked,radio/modem_debug.bin_SM-N970F,4ad824e0ae17382637892f20d4f5df384e58fc09)
$(call add-radio-file-sha1-checked,radio/param.bin_SM-N970F,536d142fa04e05364b42d11c192e04784b060c01)
$(call add-radio-file-sha1-checked,radio/sboot.bin_SM-N970F,c6e004b766fbba97700747e4f2da531efaa4071e)
$(call add-radio-file-sha1-checked,radio/uh.bin_SM-N970F,610a16f5e94bb1f495088894c14d9a779ebfdb7f)
$(call add-radio-file-sha1-checked,radio/up_param.bin_SM-N970F,9f49e38c209b04f240129d1428a3e3a0f80cd7db)
$(call add-radio-file-sha1-checked,radio/version_SM-N970F,92167d89c5cdfc317ec76291c49022e4e763242b)

endif
